Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/09/2023
Var
// Seção de Declarações das variáveis 
primeiro_num,segundo_num ,soma:inteiro
divisao:real
subtracao,multiplica: inteiro
//soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("usaurio, insira o primeiro numero: ")
leia(primeiro_num)
escreval("")

escreva(" usario,insira o segundo numero: ")
leia(segundo_num)
escreval("")

soma <- primeiro_num + segundo_num
escreval("o valor da soma e:",soma)

subtracao<- primeiro_num - segundo_num
escreval(" valor da subtracao e:",subtracao)

multiplica<-primeiro_num * segundo_num
escreval("o valor da multiplica e :",multiplica)

divisao<- primeiro_num / segundo_num
escreval("o valor da divisao e:",divisao)

Fimalgoritmo
