Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/09/2023
Var
// Seção de Declarações das variáveis 
contagem:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contagem<-0
enquanto ( contagem < 10) faca
          contagem <- contagem +1
          escreval(contagem)
fimenquanto
Fimalgoritmo