Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/09/2023
Var
// Seção de Declarações das variáveis 
opcao: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval (" bem vindo ao siri cascudo! escolha opção : ")
escreval("1- xburguer:")
escreval("2- xegg")
escreval("3- x-bacon")
escreval("4- x-tudo")
escreval("5- falar com o atendente ")

escreval(" qual a opção de lanche, voce deseja?")
leia(opcao)

escolha(opcao)
caso 1
escreval("voce escolheu x-Burguer, ja esta sendo feito.")
caso 2
escreval("voce escolheu x-Egg, ja esta sendo feito.")
caso 3
escreval("voce escolheu x-Bacon, ja esta sendo feito.")
caso 4
escreval("voce escolheu x-Tudo, ja esta sendo feito.")
caso 5
escreval("um atendente entrará em contato.")

fimescolha
fimalgoritmo


Fimalgoritmo